name: langchain_southern
channels:
  - defaults
dependencies:
  - aiodns=3.5.0
  - aiohappyeyeballs=2.6.1
  - aiohttp=3.13.2
  - aiosignal=1.4.0
  - annotated-doc=0.0.4
  - annotated-types=0.6.0
  - anyio=4.10.0
  - aom=3.12.1
  - attrs=25.4.0
  - audioop-lts=0.2.2
  - blas=1.0
  - bottleneck=1.4.2
  - brotli-python=1.2.0
  - brotlicffi=1.1.0.0
  - bzip2=1.0.8
  - c-ares=1.34.5
  - ca-certificates=2025.11.4
  - cairo=1.18.4
  - certifi=2025.11.12
  - cffi=2.0.0
  - charset-normalizer=3.4.4
  - click=8.2.1
  - dataclasses-json=0.6.7
  - dav1d=1.2.1
  - expat=2.7.3
  - fastapi=0.121.1
  - ffmpeg=6.1.1
  - ffmpy=0.3.0
  - filelock=3.20.0
  - fontconfig=2.15.0
  - freetype=2.13.3
  - fribidi=1.0.10
  - frozenlist=1.8.0
  - fsspec=2025.10.0
  - giflib=5.2.2
  - gradio=5.49.1
  - gradio-client=1.13.3
  - graphite2=1.3.14
  - greenlet=3.2.4
  - groovy-python=0.1.2
  - h11=0.16.0
  - harfbuzz=10.2.0
  - hf-xet=1.1.8
  - httpcore=1.0.9
  - httpx=0.28.1
  - httpx-sse=0.4.0
  - huggingface_hub=0.34.4
  - icu=73.1
  - idna=3.11
  - intel-openmp=2025.0.0
  - jinja2=3.1.6
  - jpeg=9f
  - jsonpatch=1.33
  - jsonpointer=3.0.0
  - langchain=0.3.27
  - langchain-community=0.3.30
  - langchain-text-splitters=0.3.11
  - langgraph=1.0.1
  - langgraph-checkpoint=3.0.0
  - langgraph-prebuilt=1.0.1
  - langgraph-sdk=0.2.9
  - langsmith=0.4.32
  - lcms2=2.17
  - leptonica=1.82.0
  - lerc=4.0.0
  - libarchive=3.8.2
  - libavif=1.3.0
  - libdeflate=1.22
  - libffi=3.4.4
  - libglib=2.84.4
  - libhwloc=2.12.1
  - libiconv=1.16
  - libmpdec=4.0.0
  - libogg=1.3.5
  - libopenjpeg=2.5.4
  - libpng=1.6.50
  - libtheora=1.2.0
  - libtiff=4.7.1
  - libuv=1.48.0
  - libvorbis=1.3.7
  - libwebp=1.6.0
  - libwebp-base=1.6.0
  - libxml2=2.13.9
  - libzlib=1.3.1
  - lz4-c=1.9.4
  - markdown-it-py=4.0.0
  - markupsafe=3.0.2
  - marshmallow=3.19.0
  - mdurl=0.1.2
  - mkl=2025.0.0
  - mkl-service=2.5.2
  - mkl_fft=2.1.1
  - mkl_random=1.3.0
  - multidict=6.7.0
  - mypy_extensions=1.0.0
  - numexpr=2.14.1
  - numpy=2.3.5
  - numpy-base=2.3.5
  - openjpeg=2.5.4
  - openssl=3.0.18
  - orjson=3.11.4
  - ormsgpack=1.11.0
  - packaging=25.0
  - pandas=2.3.3
  - pcre2=10.46
  - pillow=11.3.0
  - pip=25.3
  - pixman=0.46.4
  - propcache=0.3.1
  - pthread-stubs=0.3
  - pycares=4.10.0
  - pycparser=2.23
  - pydantic=2.11.9
  - pydantic-core=2.33.2
  - pydantic-settings=2.12.0
  - pydub=0.25.1
  - pygments=2.19.2
  - pysocks=1.7.1
  - python=3.13.9
  - python-dateutil=2.9.0post0
  - python-dotenv=1.1.0
  - python-multipart=0.0.20
  - python-tzdata=2025.2
  - python-xxhash=3.5.0
  - python_abi=3.13
  - pytz=2025.2
  - pyyaml=6.0.3
  - requests=2.32.5
  - requests-toolbelt=1.0.0
  - rich=14.2.0
  - ruff=0.12.0
  - safehttpx=0.1.7
  - semantic_version=2.10.0
  - setuptools=80.9.0
  - shellingham=1.5.4
  - six=1.17.0
  - sniffio=1.3.1
  - sqlalchemy=2.0.43
  - sqlite=3.51.0
  - starlette=0.47.3
  - tbb=2022.3.0
  - tbb-devel=2022.3.0
  - tenacity=9.1.2
  - tk=8.6.15
  - tomlkit=0.13.3
  - tqdm=4.67.1
  - typer=0.17.4
  - typing-extensions=4.15.0
  - typing-inspection=0.4.2
  - typing_extensions=4.15.0
  - typing_inspect=0.9.0
  - tzdata=2025b
  - urllib3=2.5.0
  - uvicorn=0.35.0
  - websockets=15.0.1
  - wheel=0.45.1
  - xxhash=0.8.0
  - xz=5.6.4
  - yaml=0.2.5
  - yarl=1.22.0
  - zlib=1.3.1
  - zstandard=0.24.0
  - zstd=1.5.7
  - pip:
      - aiofiles==25.1.0
      - backoff==2.2.1
      - beautifulsoup4==4.14.3
      - cryptography==46.0.3
      - emoji==2.15.0
      - faiss-cpu==1.13.1
      - filetype==1.2.0
      - html5lib==1.1
      - joblib==1.5.2
      - langchain-core==1.1.0
      - langchain-ollama==1.0.0
      - langdetect==1.0.9
      - lxml==6.0.2
      - nltk==3.9.2
      - olefile==0.47
      - ollama==0.6.1
      - psutil==7.1.3
      - pypdf==6.4.0
      - python-iso639==2025.11.16
      - python-magic==0.4.27
      - python-oxmsg==0.0.2
      - rapidfuzz==3.14.3
      - regex==2025.11.3
      - soupsieve==2.8
      - unstructured==0.18.21
      - unstructured-client==0.42.4
      - webencodings==0.5.1
      - wrapt==2.0.1
prefix: /home/brandon/anaconda3/envs/langchain_southern
